use super::ExampleContract;

pub(super) const CONTRACTS: &[ExampleContract] = &[
    (
        "virtualized_list",
        &[
            "radiant::app(",
            "virtual_list_window(",
            ".on_scroll(",
            "selectable(",
            ".update(",
        ],
    ),
    (
        "inspector_panel",
        &[
            "selectable_property_panel(",
            "PropertyRow::new(",
            ".on_change(",
        ],
    ),
    (
        "context_menu",
        &["context_menu_overlay(", "MenuItem::new(", ".danger()"],
    ),
    (
        "paint_helpers",
        &[
            "use radiant::gui::{",
            "border_fill_rects(",
            "text_field_paint(",
            "TextFieldPaint",
            "BorderSides::ALL",
        ],
    ),
    (
        "layout_diagnostics",
        &[
            "LayoutDebugOptions::all_enabled()",
            "LayoutDiagnosticCode::InvalidScrollOffsetClamped",
            "DebugPrimitiveKind::NodeBounds",
            "layout_tree_with_state(",
        ],
    ),
    (
        "rendering_benchmark",
        &[
            "surface.frame(",
            "paint_plan.stats()",
            "radiant_rendering_benchmark",
        ],
    ),
    (
        "host_surface_frame",
        &[
            "SurfaceRuntime::new(",
            "dispatch_event(Event::PointerMove",
            "runtime.borrowed_frame_into(&theme",
            "paint_plan.stats()",
            "radiant_host_surface_frame",
        ],
    ),
    (
        "passive_widgets",
        &[
            "radiant::window(",
            "passive_button(",
            "passive_toggle(",
            "passive_text_input(",
            "canvas()",
            "spacer()",
        ],
    ),
    (
        "split_workspace",
        &[
            "SplitPaneSidebarState",
            "SplitPaneSlot",
            "assign_selected_to",
            "pane_view(",
        ],
    ),
    (
        "node_editor",
        &[
            "retained_canvas(",
            "drop_marker(",
            "drag_handle()",
            "selectable(",
        ],
    ),
    (
        "timeline_editor",
        &[
            "TimelineSurfaceParts",
            "TimelineSurfaceState::from_parts(",
            "TimelineEditPreviewParts",
            "TimelineEditPreview::from_parts(",
            "TimelineMotionState::new(",
            "SignalToolFlags",
            "retained_canvas(",
            "custom_widget_mapped(",
            "prefers_pointer_move_paint_only",
            "append_runtime_overlay_paint",
            "drag_handle_at_point",
        ],
    ),
    (
        "spectrogram",
        &[
            "Realtime Spectrogram",
            ".animation(|state| state.running)",
            ".on_frame(|| SpectrogramMessage::Frame)",
            "PaintPrimitive::FillRect",
            "prefers_pointer_move_paint_only",
            "append_runtime_overlay_paint",
            "spectrogram_runtime_hover_does_not_refresh_surface",
            "generate_spectral_column",
            "without_dsp",
        ],
    ),
];
