use super::ExampleContract;

pub(super) const CONTRACTS: &[ExampleContract] = &[
    (
        "virtualized_list",
        &[
            "radiant::app(",
            "virtual_list_window(",
            ".on_scroll(",
            "selectable(",
            ".update(",
        ],
    ),
    (
        "inspector_panel",
        &[
            "selectable_property_panel(",
            "PropertyRow::new(",
            ".on_change(",
        ],
    ),
    (
        "context_menu",
        &["context_menu_overlay(", "MenuItem::new(", ".danger()"],
    ),
    (
        "paint_helpers",
        &[
            "use radiant::gui::{",
            "border_fill_rects(",
            "text_field_paint(",
            "TextFieldPaint",
            "BorderSides::ALL",
        ],
    ),
    (
        "layout_diagnostics",
        &[
            "LayoutDebugOptions::all_enabled()",
            "LayoutDiagnosticCode::InvalidScrollOffsetClamped",
            "DebugPrimitiveKind::NodeBounds",
            "layout_tree_with_state(",
        ],
    ),
    (
        "rendering_benchmark",
        &[
            "surface.frame(",
            "paint_plan.stats()",
            "radiant_rendering_benchmark",
        ],
    ),
    (
        "host_surface_frame",
        &[
            "SurfaceRuntime::new(",
            "dispatch_event(Event::PointerMove",
            "runtime.borrowed_frame_into(&theme",
            "paint_plan.stats()",
            "radiant_host_surface_frame",
        ],
    ),
    (
        "passive_widgets",
        &[
            "radiant::window(",
            "passive_button(",
            "passive_toggle(",
            "passive_text_input(",
            "canvas()",
            "spacer()",
        ],
    ),
    (
        "split_workspace",
        &[
            "SplitPaneSidebarState",
            "SplitPaneSlot",
            "assign_selected_to",
            "pane_view(",
        ],
    ),
    (
        "node_editor",
        &[
            "retained_canvas(",
            "drop_marker(",
            "drag_handle()",
            "selectable(",
        ],
    ),
    (
        "timeline_editor",
        &[
            "TimelineSurfaceParts",
            "TimelineSurfaceState::from_parts(",
            "TimelineEditPreviewParts",
            "TimelineEditPreview::from_parts(",
            "TimelineMotionState::new(",
            "SignalToolFlags",
            "retained_canvas(",
            "custom_widget_mapped(",
            "prefers_pointer_move_paint_only",
            "append_runtime_overlay_paint",
            "drag_handle_at_point",
        ],
    ),
    (
        "spectrogram",
        &[
            "Realtime Spectrogram",
            ".animation(|state| state.running)",
            ".on_frame(|| SpectrogramMessage::Frame)",
            "PaintPrimitive::FillRect",
            "prefers_pointer_move_paint_only",
            "append_runtime_overlay_paint",
            "spectrogram_runtime_hover_does_not_refresh_surface",
            "generate_spectral_column",
            "without_dsp",
        ],
    ),
    (
        "mixer_console",
        &[
            "32-Channel Mixer",
            ".animation(|state| state.running)",
            ".on_frame(|| MixerMessage::Frame)",
            "MixerPanelWidget::new",
            "ListSelectionController",
            "ListSelectionModifiers",
            "SetSend",
            "Reorder",
            "insertion_line_rect",
            "mixer_strip_drag_paints_insertion_line_without_spreading_strips",
            "mixer_strip_drag_drop_emits_reorder_message",
            "mixer_group_fader_drag_applies_relative_gain_delta_to_selected_channels",
            "SEND_COUNT",
            "PaintPrimitive::FillRect",
            "prefers_pointer_move_paint_only",
            "append_runtime_overlay_paint",
            "mixer_runtime_hover_does_not_refresh_surface",
            "mixer_tick_animates_synthetic_decibel_meters_without_dsp",
            "without_dsp",
        ],
    ),
    (
        "piano_roll",
        &[
            "Piano Roll",
            ".animation(|state| state.running)",
            ".on_frame(|| AppMessage::Frame)",
            "PianoRollWidget::new",
            "PianoRollMessage::CreateNote",
            "PianoRollMessage::MoveNote",
            "PianoRollMessage::ResizeNote",
            "prefers_pointer_move_paint_only",
            "append_runtime_overlay_paint",
            "piano_roll_runtime_hover_does_not_refresh_surface",
            "piano_roll_tick_advances_synthetic_playhead_without_midi_or_dsp",
            "without_midi_or_dsp",
        ],
    ),
    (
        "modulation_matrix",
        &[
            "Modulation Matrix",
            ".animation(|state| state.running)",
            ".on_frame(|| AppMessage::Frame)",
            "ModulationMatrixWidget::new",
            "MatrixMessage::SetAmount",
            "MatrixMessage::ClearSelected",
            "prefers_pointer_move_paint_only",
            "append_runtime_overlay_paint",
            "modulation_matrix_runtime_hover_does_not_refresh_surface",
            "modulation_matrix_tick_advances_synthetic_activity_without_synth_or_dsp",
            "without_synth_or_dsp",
        ],
    ),
    (
        "arrangement_shell",
        &[
            "Arrangement Shell",
            ".animation(|state| state.running)",
            ".on_frame(|| AppMessage::Frame)",
            "ArrangementOverviewWidget::new",
            "ShellMessage::SelectClip",
            "ShellMessage::Seek",
            "ToggleBrowser",
            "ToggleInspector",
            "prefers_pointer_move_paint_only",
            "append_runtime_overlay_paint",
            "arrangement_shell_runtime_hover_does_not_refresh_surface",
            "arrangement_shell_tick_advances_playhead_and_meters_without_audio_or_dsp",
            "without_audio_or_dsp",
        ],
    ),
];
