use super::ExampleContract;

pub(super) const CONTRACTS: &[ExampleContract] = &[
    (
        "folder_browser",
        &[
            "use radiant::prelude as ui;",
            "RADIANT_FOLDER_BROWSER_ROOT",
            "BrowserState::from_root(",
            "view::project_surface",
            "ui::message_context_menu_overlay(",
            "ui::MenuCommand::new(",
            "examples/folder_browser/actions.rs",
            "examples/folder_browser/file_view.rs",
            "examples/folder_browser/storage.rs",
            "examples/folder_browser/tests.rs",
        ],
    ),
    (
        "waveform_view",
        &[
            "GpuSurfaceContent::SignalSummaryBands",
            ".animated_transient_overlay_at(",
            "paint_playhead_overlay(",
            "first_widget_rect(",
            "waveform_playback_uses_paint_only_transient_playhead",
        ],
    ),
    (
        "multi_window_manifest",
        &[
            "radiant::window(",
            ".spec(",
            "WindowSpec::new(",
            "build_window_views()",
        ],
    ),
    (
        "popup_window",
        &[
            ".floating_popup()",
            ".popup_policy(",
            "NativePopupOptions::default()",
            "WindowSpec::popup(",
            "workflow-popup",
            "OpenPopup",
            "PopupMessage::Close",
            "popup_view(",
            "examples/popup_window/host.rs",
            "examples/popup_window/host/child.rs",
            "examples/popup_window/model.rs",
            "examples/popup_window/platform.rs",
            "examples/popup_window/policy.rs",
            "hide_after_first_present",
            "park_visible_offscreen_show_path",
            "focus_popup_after_reveal",
            "focus_popup_window",
            "wait_for_visible_popup_window",
            "PopupHosts",
        ],
    ),
    (
        "typography",
        &[
            ".wrap()",
            ".truncate()",
            ".baseline(",
            ".align_text(",
            "TextAlign::Center",
        ],
    ),
    (
        "layout_rows_columns",
        &["row([", "column([", ".padding(", ".fill_width()"],
    ),
    (
        "grid_gallery",
        &[
            "grid_with_gaps(",
            ".wrap()",
            ".fill()",
            "WidgetTone::Accent",
        ],
    ),
    (
        "widget_gallery",
        &["badge(", "selectable(", "card()", "stack(["],
    ),
    ("list", &["list(", "list_row(", ".fill_height()"]),
    (
        "tree_and_details",
        &[
            "tree_list_with_drag(",
            "selectable_sortable_details_list(",
            "DetailsColumn::fixed(",
            "DetailsSort::new(",
            "DragHandleMessage",
        ],
    ),
];
