//! Backend-neutral GUI model and helper prelude exports.

pub use crate::gui::paint::BorderSides;
pub use crate::gui::types::{ImageRgba, ImageRgbaError, Point, Rect, Rgba8, Vector2};
pub use crate::gui::{
    badge::{
        InlineBadgeMetrics, InlineBadgeMetricsParts, inline_badge_cluster_reserved_width,
        inline_badge_height, inline_badge_labels, inline_badge_labels_owned,
        inline_badge_labels_owned_into, inline_badge_rects, inline_badge_rects_for_labels,
        inline_badge_rects_for_labels_into, inline_badge_rects_into, inline_badge_text_origin,
        inline_badge_text_width, inline_badge_width, inline_badge_width_in_range,
    },
    chrome::{
        ContentViewActivityChrome, ContentViewChrome, ContentViewFooterChrome,
        ContentViewSearchChrome, ContentViewSortChrome, ContentViewTabs, StatusSegments,
        StatusSegmentsParts,
    },
    disclosure::ExclusiveOpen,
    feedback::{
        ProgressSnapshot, ProgressUpdateGate, StatusLineEntry, StatusLineEntryParts, StatusLineLog,
        horizontal_progress_fill_rect, horizontal_value_cursor_rect,
        horizontal_value_range_edge_rects, horizontal_value_range_rect,
        horizontal_wrapped_value_range_rects, push_horizontal_value_cursor_fill,
        push_horizontal_value_range_edge_fills, push_horizontal_value_range_fill,
        vertical_bipolar_fill_rect, vertical_bipolar_value_at_point, vertical_center_track_rect,
        vertical_meter_lane_fill_rect, vertical_value_at_point, vertical_value_knob_rect,
        vertical_value_line_rect,
    },
    flow::{
        FlowItem, FlowItemWidth, FlowLayoutMetrics, FlowLayoutMetricsParts, FlowTrailingItemParts,
        flow_row_width, flow_rows_height, flow_trailing_item_starts_new_row, pack_flow_rows,
        pack_flow_rows_with_trailing_item, push_flow_row_group, push_flow_row_item,
    },
    focus::FocusSurface,
    frame::{FrameCadenceConfig, FrameCadenceKind, FrameCadenceMonitor, FrameCadenceReport},
    input::{KeyCode, KeyPress},
    invalidation::{
        InvalidationMask, RetainedSegment, RetainedSegmentKind, RetainedSegmentMask,
        RetainedSegmentPlan, RetainedSegmentRevisions, RevisionCounter,
    },
    layout_core::StackedLayoutCursor,
    list::{
        ColumnSummary, ColumnSummaryParts, CyclicListSelectionCycle, DenseRowLabelParts,
        DenseRowMarkerEdge, DenseRowMarkerParts, DenseRowPalette, DenseRowVisualState,
        KeyedListSelection, ListSelectionController, ListSelectionIntent, ListSelectionModifiers,
        VirtualListController, VirtualListStackMetrics, VirtualListStackMetricsParts,
        VirtualListWindow, VirtualListWindowRequest, bounded_list_height,
        bounded_list_visible_rows, cyclic_list_index_after_delta, dense_row_fill_color,
        dense_row_inset_rect, dense_row_label_font_size, dense_row_vertical_marker_rect,
        list_index_after_delta, push_dense_row_fill, push_dense_row_inset_stroke,
        push_dense_row_label, push_dense_row_vertical_marker, resolve_virtual_list_window,
        virtual_list_view_start_for_scroll_offset,
    },
    paint::{horizontal_line_rect, vertical_line_rect},
    panel::{PanelResizeDrag, PanelResizeEdge, update_panel_resize_drag},
    range::{
        IndexViewport, NormalizedRange, NormalizedRangeDrag, NormalizedRangeEdge,
        normalized_fraction_to_micros, normalized_fraction_to_milli, normalized_fraction_to_nanos,
    },
    selection::SelectionSet,
    shortcuts::{
        ShortcutGesture, ShortcutLayer, ShortcutModifier, ShortcutResolution, ShortcutStack,
    },
    svg::{SvgIcon, SvgIconTintCache, svg_with_current_color},
    text_layout::{
        TextLineInsets, TextWidthEstimate, centered_text_baseline, centered_text_line,
        estimated_text_width, estimated_text_width_for_char_count,
        estimated_text_width_for_char_count_in_range, estimated_text_width_in_range, top_text_line,
    },
    undo::{UndoCheckpoint, UndoHistory, UndoRedoIntent, UndoTransition},
    visualization::{
        CanvasInvalidation, CanvasLayer, CanvasLayerOrder, CanvasLayerParts,
        CanvasSelectionBodyHandleParts, CanvasSelectionGeometry, CanvasSelectionGeometryParts,
        ColorRamp, ColorRampStop, DenseGridCell, DenseGridLabelLayout, DenseGridLabelLayoutParts,
        DenseGridLayout, DenseGridLayoutParts, DenseGridRasterLayout, DenseGridRasterLayoutParts,
        DenseGridRowOrigin, DragHandle, DragHandleRole, HorizontalLogValueAxis,
        HorizontalLogValueAxisParts, HorizontalStripLayout, HorizontalStripLayoutParts,
        HorizontalValueAxis, HorizontalValueAxisParts, SampledCurveStrokeParts, TimelineAxis,
        TimelineAxisParts, TimelineCoordinateMapper, TimelineEditHandle,
        TimelineEditHandleGeometry, TimelineEditPreview, TimelineEditPreviewParts,
        TimelineItemLayout, TimelineItemLayoutParts, TimelineLaneLayout, TimelineLaneLayoutParts,
        TimelinePanelLayout, TimelinePanelLayoutParts, TimelinePitchItemLayout,
        TimelinePitchItemLayoutParts, TimelinePitchLayout, TimelinePitchLayoutParts,
        TimelineValueMarkerLayout, TimelineValueMarkerLayoutParts, TimelineViewport,
        TimelineViewportParts, VerticalStripStackLayout, VerticalStripStackLayoutParts,
        VerticalStripStackOrigin, VerticalValueAxis, VerticalValueAxisParts, canvas_layer_at_point,
        canvas_selection_body_handle_rect, canvas_selection_edge_handles,
        canvas_selection_edge_visual_rect, canvas_selection_rect,
        canvas_selection_trailing_control_rect, drag_handle_at_point,
        horizontal_resize_edge_bracket_rects, push_sampled_curve_stroke, sampled_curve_points,
    },
};
